### PR TITLE
Added dropdown to select map icons

### PR DESCRIPTION
**Pull request by spookirs**
My take on #3 . :)

LMK if I can improve on the contribution in any way. I'm very eager to contribute.

Thanks.

### CODE REVIEW

**Comment by willismonroe** [comment]
Nice start, since the left hand side is dedicated to searching, lets more the symbol selector to the right hand side. Also it would be good to leave the default as the the square icon (☐).

**Comment by spookirs** [comment]
Got it, I'll update the pull request soon.

**Comment by spookirs** [comment]
@willismonroe updated.

**Comment by willismonroe** [comment]
Something is weird with the rendering on your pr the map renders like this: 
image

Whereas on the live version it looks like this: 
image

**Comment by spookirs** [comment]
Haven't noticed that. I'll have a look. 👍

**Comment by spookirs** [comment]
Now it should be fixed @willismonroe 

>  leave the default as the the square icon (☐).

I copied this one which is actually a different character from the live version.

The default icon is now □ instead of ☐

**Comment by willismonroe** [comment]
Thanks @miikisalminen well done!

**Pull request merged**
